### ISSUE TITLE
translate NLP Newsletter issues

### ISSUE THREAD

**Issue by omarsar** [dair-ai/dair-ai.github.io#11]
These are the tasks for translating the NLP Newsletter issues. If you are interested in translating any of the issues in the [NLP Newsletter](https://dair.ai/newsletter/) to your own language please feel free to comment below and we can add it to the list of tasks. 

If you are working on a translation on any of the NLP Newsletter issues below, just comment "I am working on [Issue number] for [Language] language" in the comment section, then open a separate issue with the following title "NLP Newsletter [Issue number] for [Language] language" and link back that issue in your comment below. _Please note that after the completion of the translation task, I will remove the related comments so as to keep things clean below._ 

You can post the translation anywhere you like (e.g., Medium, your personal website), I only ask permission to repost the translation back on [dair.ai](https://dair.ai/) for accessibility purposes. If you would like to directly submit the translation as a PR to the dair.ai website you can check this [guide](https://gist.github.com/omarsar/e1b6d38d5b727999f01e93396628c0b2). 

UPDATE: _In order to bring more awareness to these translations, I will share them in some social media sites and I will also be featuring them in the upcoming weekly NLP Newsletter._ 

[**NLP Newsletter (Issue 13)**](https://dair.ai/NLP_Newsletter_13_en/)
- [ ] Chinese
- [ ] Arabic
- [ ] Spanish
- [ ] Brazilian Portuguese (PT-BR)
- [ ] Turkish
- [ ] French
- [ ] Your Language

[**NLP Newsletter (Issue 12)**](https://dair.ai/NLP_Newsletter_12_en/)
- [ ] Chinese
- [ ] Arabic
- [ ] Spanish
- [ ] Brazilian Portuguese (PT-BR)
- [ ] Turkish
- [ ] [French](https://dair.ai/NLP_Newsletter_-12_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 11)**](https://dair.ai/NLP_Newsletter_11_en/)
- [ ] Chinese
- [ ] Arabic
- [ ] Spanish
- [ ] Brazilian Portuguese (PT-BR)
- [x] [Turkish](https://dair.ai/NLP_Newsletter_11_tr/)
- [x] [French](https://dair.ai/NLP_Newsletter_-11_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 10)**](https://dair.ai/NLP_Newsletter_10_en/)
- [x] [Chinese](https://dair.ai/NLP_Newsletter_NLP_10-ZH/)
- [ ] Arabic
- [ ] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_10/)
- [x] [Turkish](https://dair.ai/NLP_Newsletter_10_-TR/)
- [x] [French](https://dair.ai/NLP_Newsletter_10_FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 9)**](https://dair.ai/NLP_Newsletter_9/)
- [x] [Chinese](https://dair.ai/NLP_Newsletter_NLP_9-ZH/)
- [ ] Arabic
- [ ] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter_9_-PT-BR/)
- [x] [Turkish](https://dair.ai/NLP_Newsletter_9_-TR/)
- [x] [French](https://dair.ai/NLP_Newsletter_-9_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 8)**](https://dair.ai/NLP_Newsletter_8/)
- [x] [Chinese](https://dair.ai/NLP_Newsletter_NLP_8-ZH-.md/)
- [ ] Arabic
- [ ] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_8/)
- [x] [Turkish](https://dair.ai/NLP_Newsletter_8_-TR/)
- [x] [French](https://dair.ai/NLP_Newsletter_-8_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 7)**](https://dair.ai/NLP_Newsletter_NLP_7/)
- [x] [Chinese](https://dair.ai/NLP_Newsletter_NLP_7-ZH-.md/)
- [ ] Arabic
- [ ] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_NLP_7/)
- [ ] Turkish
- [x] [French](https://dair.ai/NLP_Newsletter_-7_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 6)**](https://dair.ai/NLP_Newsletter_BERTology_Primer_fastpages_T5/)
- [x] [Chinese](https://dair.ai/NLP%E7%AE%80%E6%8A%A5/)
- [ ] Arabic
- [ ] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_BERTology_Primer_fastpages_T5/)
- [ ] Turkish
- [x] [French](https://dair.ai/NLP_Newsletter_-6_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 5)**](https://dair.ai/NLP_Newsletter_The_Annotated_GPT-2,_Understanding/)
- [x] [Chinese](https://dair.ai/NLP%E7%AE%80%E6%8A%A5-Issue-5-The_Annotated_GPT-2-CodeBERT-JAX-GA/)
- [x] [Arabic](https://dair.ai/NLP_Newsletter.AR._The_Annotated_GPT-2_And_More/)
- [x] [Spanish](https://dair.ai/Bolet%C3%ADn_informativo_NLP_GPT-2_Explicado,_Entendie/)
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_The_Annotated_GPT-2,_Understanding/)
- [ ] Turkish
- [x] [French](https://dair.ai/NLP_Newsletter_-5_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 4)**](https://dair.ai/NLP_Newsletter_PyTorch3D,_DeepSpeed,_Turing-NLG/) 
- [x] [Chinese](https://dair.ai/NLP%E7%AE%80%E6%8A%A5_ISSUE_4_PyTorch3D,_DeepSpeed,_Turing-NLG/)
- [ ] Arabic
- [x] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_PyTorch3D,_DeepSpeed,_Turing-NLG/)
- [ ] Turkish
- [x] [French](https://dair.ai/NLP_Newsletter_-4_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 3)**](https://dair.ai/NLP_Newsletter_Flax,_Thinc,_Language-specific_BERT/) 
- [x] [Chinese](https://dair.ai/NLP%E7%AE%80%E6%8A%A5_Flax,_Thinc,_Language-specific_BERT_models/)
- [ ] Arabic
- [x] Spanish
- [ ] Brazilian Portuguese (PT-BR)
- [ ] Turkish
- [x] [French](https://dair.ai/NLP_Newsletter_-3_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 2)**](https://dair.ai/NLP_Newsletter_Reformer,_DeepMath,_ELECTRA,_TinyB-copy/)
- [x] [Chinese](https://dair.ai/NLP%E7%AE%80%E6%8A%A5_Reformer,_DeepMath,_ELECTRA,_TinyBERT/)
- [ ] [Arabic]
- [ ] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_Reformer,_DeepMath,_ELECTRA,_TinyB/)
- [ ] Turkish
- [x] [French](https://dair.ai/NLP_Newsletter_-2_-FR/)
- [ ] Your Language

[**NLP Newsletter (Issue 1)**](https://dair.ai/NLP_Newsletter_Tokenizers,_TensorFlow_2_1,_TextVe/) 
- [x] [Chinese](https://dair.ai/NLP%E7%AE%80%E6%8A%A5_Tokenizers,_TensorFlow_2_1,_TextVectorization/)
- [ ] Arabic
- [ ] Spanish
- [x] [Brazilian Portuguese (PT-BR)](https://dair.ai/NLP_Newsletter-PT-BR-_Tokenizers,_TensorFlow_2_1,_TextVe/)
- [ ] Turkish
- [x] [French](https://dair.ai/NLP_Newsletter_-1_-FR/)
- [ ] Your Language

**Comment by fclesio** [comment]
Portuguese.

**Comment by VictorGarritano** [comment]
I am working on Issue 4 for Brazilian Portuguese language

**Comment by haneybarg** [comment]
I am working on Issue 1 for Brazilian Portuguese language.

**Comment by omarsar** [comment]
@angysaravia working on Issue 4 for Spanish language (#15)

**Comment by fclesio** [comment]
I'm working on news letter 2 for Brazilian Portuguese language (https://github.com/dair-ai/dair-ai.github.io/issues/16)

**Comment by KaiyuanGao** [comment]
I am working on Issue 5 for Chinese language[（#25）](https://github.com/dair-ai/dair-ai.github.io/issues/25)

**Comment by omarsar** [comment]
@fclesio decided to take on the translation for PT-BR for Issue 5. 🙏 #22

**Comment by SufianDira** [comment]
I am working on Issue #5 for the Arabic language

**Comment by omarsar** [comment]
@SufianDira I have created a separate issue for the task you chose. Refer to #26 
Thanks!

**Comment by naraquev** [comment]
I am working on NLP Newsletter (Issue 5) for Spanish Language

**Comment by KaiyuanGao** [comment]
I am working on NLP Newsletter (Issue 6) for Chinese Language

**Comment by omarsar** [comment]
@naraquev and @KaiyuanGao thanks for doing this. Please try to open a separate issue to manage those tasks individually.

**Comment by VictorGarritano** [comment]
I am working on Issue 6 for Brazilian Portuguese language (#36 )

**Comment by VictorGarritano** [comment]
I am working on Issue 7 for Brazilian Portuguese language (#45 )

**Comment by KaiyuanGao** [comment]
I am working on Issue 7 for Chinese language (#47 )

**Comment by KaiyuanGao** [comment]
I am working on Issue 8 for Chinese language (#52 )

**Comment by VictorGarritano** [comment]
I am working on Issue 8 for Brazilian Portuguese language (#53 )

**Comment by harunuz** [comment]
I am working on Issue 8 for Turkish language

**Comment by haneybarg** [comment]
I am working on Issue 9 for Brazilian Portuguese language.

**Comment by KaiyuanGao** [comment]
I am working on Issue 9 for Chinese language. #61

**Comment by harunuz** [comment]
I am working on Issue 9 for Turkish language

**Comment by VictorGarritano** [comment]
I am working on Issue 10 for Brazilian Portuguese Language

**Comment by harunuz** [comment]
I am working on Issue 10 for Turkish language

**Comment by KaiyuanGao** [comment]
I am working on Issue 10 for Chinese language #100

**Comment by harunuz** [comment]
I am working on 11 for TR language #106

**Comment by franfj** [comment]
I am working on Issue 12 for Spanish language. #124
