### ISSUE TITLE
NLP Newsletter #1 [Brazilian Portuguese]

### ISSUE THREAD

**Issue by haneybarg** [dair-ai/dair-ai.github.io#13]

**Comment by haneybarg** [comment]
Hi @omarsar , I just finished the translation. Can you give push access to the repository, please? After that I will open a pull request with the translated markdown file, following your guide.

**Comment by omarsar** [comment]
Hi @haneybarg, I have sent you an invite to push to the repo. Also, let me know if you would like me to add your authorship information along with the translation. If yes, I would need your info and photo as requested in the guide. Thanks.

**Comment by haneybarg** [comment]
Hi @omarsar, there is no need to add my authorship info. Thanks.

**Comment by omarsar** [comment]
Perfect! In that case, I will review the PR and you can merge to master once it's ready.
