### ISSUE TITLE
Idea for an article

### ISSUE THREAD

**Issue by abhi1nandy2** [dair-ai/dair-ai.github.io#130]
In today's world, annotators find it really difficult to keep up with a myriad of unlabeled datasets waiting to get annotated in order to perform supervised and semi supervised tasks on them, especially when the task is time taking and strenuous, such as summarisation, language translation etc. In order to bridge this gap between annotation and unlabeled data, and at the same time, set up a machine which is able to perform many such tasks efficiently, meta-learning, or 'learning to learn' comes to the rescue. Hence, @omarsar, I would like to write an article discussing Meta-learning, a brief history on its evolution, and it's implications on contemporary research.

**Comment by omarsar** [comment]
@abhi1nandy2 This is a great idea and it's very relevant to the kind of stuff we publish. Please reach out to our editors' team at the #editor channel in our Slack group and we can provide you some guidance about how we review content and publish. You can ask any other questions that you have there. Thanks.

**Comment by abhi1nandy2** [comment]
> @abhi1nandy2 This is a great idea and it's very relevant to the kind of stuff we publish. Please reach out to our editors' team at the #editor channel in our Slack group and we can provide you some guidance about how we review content and publish. You can ask any other questions that you have there. Thanks.

Thank you!
