### ISSUE TITLE
NLP Newsletter #2 [Brazilian Portuguese]

### ISSUE THREAD

**Issue by fclesio** [dair-ai/dair-ai.github.io#16]

**Comment by fclesio** [comment]
@omarsar I finished the translation but I would like to know what page or template should I change to submit the PR for review.

**Comment by omarsar** [comment]
@fclesio Please follow this [guide](https://gist.github.com/omarsar/e1b6d38d5b727999f01e93396628c0b2) for instructions on how to submit the PR to the publication. If something is not clear or you need help with anything, let me know.

**Comment by fclesio** [comment]
Requested @omarsar
