### ISSUE TITLE
Call for Research Paper Summaries

### ISSUE THREAD

**Issue by omarsar** [dair-ai/dair-ai.github.io#23]
Over the years as a researcher, I have found that summarizing papers allows me to dive deep into understanding certain concepts and explain them clearly to others. It's important to be able to summarize a paper using simple words and avoiding jargon, to reach a broader audience and make a topic more accessible and approachable. It's an important skill as you will also learn in the process how to question the claims made and possibly even come up with your own research topics, ideas, and discussions.

This issue is a call for submitting ML and NLP paper summaries or research articles to be published on [dair.ai](https://dair.ai/). To simplify the process of selection, I will also list my suggestions for topics and papers (from ML and NLP) worth summarizing and that could be interesting/useful for our community. Typically, I select papers that present an interesting dataset, new problem/task, important ablation study, state-of-the-art results, interpretability/explainability, and other pressing issues and emerging topics in ML and NLP. You can also make suggestions of topics/papers below if you are interested in writing about a topic not listed here.

Once we have agreed on and identified the paper/topic you want to write about, you can create a separate issue so that everyone knows that you are working on that particular paper/topic. We will maintain and track all paper summary tasks in this parent issue (#27). This allows others to contribute, get informed, give feedback, and even collaborate in the process. This also means that I will be able to give you feedback and mentor you throughout the whole process before publishing on [dair.ai](https://dair.ai/). I also welcome other mentors to participate in the discussion and provide feedback. Once published, we will also reshare your work with everyone on social media and other sites so as to bring your work more visibility. 

If you are interested in contributing to dair.ai in this regard, feel free to comment below. It doesn't have to be a long article, the summary can aim to answer the following key questions:

**- Why is it important?**
  - Discuss the reason why this paper matters
  - Motivate it with examples of its applications

**- What it is?**
  - Introduce the method/techniques/dataset/etc presented and what problem/s it approaches?
  - How does the method/technique/dataset/etc contribute to solving the problem?

**- How does it work?**
  - This goes hand-in-hand with the previous question; here you aim to expound on the details and pick out the insights/themes that are worth discussing (e.g., a new data augmentation technique)
  - Does the method provide some insights that can be used in other types of research?

**- What's next?**
  - Explain the interesting and exciting research directions that can come from such research

I am planning to do a live online mentor session to talk more about this idea, so that's coming soon. If you have questions feel free to reach out at ellfae@gmail.com or [DM me on Twitter](https://twitter.com/omarsar0).

Here are some examples of paper summaries that I have written in the past.
- [Deep Learning for NLP: An Overview of Recent Trends](https://medium.com/dair-ai/deep-learning-for-nlp-an-overview-of-recent-trends-d0d8f40a776d)
- [An Overview of Troubling Trends in Machine Learning Scholarship](https://medium.com/dair-ai/an-overview-of-troubling-trends-in-machine-learning-scholarship-582df3caa518)
- [Aspects of language captured by BERT](https://medium.com/dair-ai/aspects-of-language-captured-by-bert-32bc3c54016f)
- [XLNet outperforms BERT on several NLP Tasks](https://medium.com/dair-ai/xlnet-outperforms-bert-on-several-nlp-tasks-9ec867bb563b)
- [A Light Introduction to Transformer-XL](https://medium.com/dair-ai/a-light-introduction-to-transformer-xl-be5737feb13)
- [HMTL: Multi-task learning for state of the art NLP](https://medium.com/dair-ai/examining-gender-and-race-bias-in-sentiment-analysis-systems-b04b269a653)
- [A Light Introduction to Transfer Learning for NLP](https://medium.com/dair-ai/a-light-introduction-to-transfer-learning-for-nlp-3e2cb56b48c8)
- [State of the art Multimodal Sentiment Classification in Videos](https://medium.com/dair-ai/state-of-the-art-multimodal-sentiment-classification-in-videos-1daa8a481c5a)
- [Detecting Emotions with CNN Fusion Models](https://medium.com/dair-ai/detecting-emotions-with-cnn-fusion-models-b066944969c8)
- [Detecting Sarcasm with Deep Convolutional Neural Networks](https://medium.com/dair-ai/detecting-sarcasm-with-deep-convolutional-neural-networks-4a0657f79e80)
- [Using Deep Learning to Detect Linguistic Cues of Alzheimer’s Disease Patients](https://medium.com/dair-ai/using-deep-learning-to-detect-linguistic-cues-of-alzheimers-patients-a606693e54f9)

[Papers/Topic to be announced #27]

**Comment by fclesio** [comment]
+1 to contribute here. 

Are you thinking more in classic articles (_e.g._ Breiman _Statistical Modeling: The Two Cultures_) or more SOTA with modern techniques (_e.g._ Attention it's all you need)?

**Comment by omarsar** [comment]
@fclesio I am aiming for more modern techniques/papers but revisiting classical articles could also be interesting for the community. At the end of the day, the idea is for readers to get a nice overview of something we think could be useful and of interest to them. I find historical conversations to be fascinating. SOTA is important in some sense but I also think that we can focus on other aspects of this type of research such as methods for accessibility, conversations around ethical considerations, low-resource languages, survey papers, improving metrics, dataset releases, among other pressing issues and topics.

**Comment by omarsar** [comment]
Move to Wiki
