### ISSUE TITLE
Ongoing Paper Summaries

### ISSUE THREAD

**Issue by omarsar** [dair-ai/dair-ai.github.io#27]
In this issue, I will maintain a few ML and NLP research papers that I have identified to be worth summarizing. Read more about this initiative here #23.

If you are interested in working together on any of the papers to be published on [dair.ai](https://dair.ai/), leave your comment below and we will open a new issue where each task will be tracked individually. Feel free to open the issue yourself and link it back to this issue.

If you have any further questions about the process or this project look at our [Wiki](https://github.com/dair-ai/dair-ai.github.io/wiki) or join our [Slack](https://join.slack.com/t/dairai/shared_invite/zt-dv2dwzj7-F9HT047jIGkunNKv88lQ~g) group to ask for help (I recommend asking in the #help channel).

Papers that have already been assigned will be tagged with the GitHub username of the author.

_Feel free to add your suggestions in the comment section below and we can add the paper to the list._

**Papers to summarize**
- [x] [Recipes for building an open-domain chatbot](https://arxiv.org/abs/2004.13637)(@cfierro94)
- [ ] [Climbing towards NLU: On Meaning, Form, and Understanding in the Age of Data](https://openreview.net/forum?id=GKTvAcb12b)
- [ ] [Experience Grounds Language](https://arxiv.org/abs/2004.10151) (@omarsar)
- [ ] [DialoGPT: Large-Scale Generative Pre-training for Conversational Response Generation](https://www.microsoft.com/en-us/research/publication/dialogpt-large-scale-generative-pre-training-for-conversational-response-generation/)
- [ ] [Weight Poisoning Attacks on Pre-trained Models](https://arxiv.org/abs/2004.06660)
- [ ] [Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer](https://arxiv.org/abs/1910.10683)
- [ ] [Byte Pair Encoding is Suboptimal for Language Model Pretraining](https://arxiv.org/abs/2004.03720)(assigned to @skeshaw)
- [ ] [Evaluating Machines by their Real-World Language Use](https://arxiv.org/abs/2004.03607)
- [ ] [XTREME: A Massively Multilingual Multi-task Benchmark for Evaluating Cross-lingual Generalization](https://arxiv.org/abs/2003.11080)
- [ ] [Rapidly Deploying a Neural Search Engine for the COVID-19 Open Research Dataset: Preliminary Thoughts and Lessons Learned](https://openreview.net/forum?id=PlUA_mgGaPq) [assigned to @manisnesan]
- [ ] [ELECTRA: PRE-TRAINING TEXT ENCODERS AS DISCRIMINATORS RATHER THAN GENERATORS](https://openreview.net/pdf?id=r1xMH1BtvB) (assigned to @ngc436)
- [ ] [Revealing the Dark Secrets of BERT](https://towardsdatascience.com/beyond-bert-6f51a8bc5ce1)
- [ ] [Reformer: The Efficient Transformer](https://arxiv.org/abs/2001.04451) (assigned to @AntonioLopardo)
- [ ] [REALM: Retrieval-Augmented Language Model Pre-Training](https://kentonl.com/pub/gltpc.2020.pdf)
- [ ] [ERNIE 2.0: A Continual Pre-training Framework for Language Understanding](https://arxiv.org/abs/1907.12412) (@laibamehnaz)
- [ ] [A Primer in BERTology: What we know about how BERT works
](https://arxiv.org/abs/2002.12327) (assigned to @vsistla)
- [ ] [Towards a Human-like Open-Domain Chatbot](https://arxiv.org/abs/2001.09977)
- [ ] [Neural Approaches to Conversational AI](https://arxiv.org/abs/1809.08267)
- [ ] [Neural Transfer Learning for Natural Language Processing](https://ruder.io/thesis/neural_transfer_learning_for_nlp.pdf)
- [ ] [The Role of Cooperation in Responsible AI Development
](https://arxiv.org/abs/1907.04534)
- [ ] [Scaling Laws for Neural Language Models](https://arxiv.org/abs/2001.08361)
- [ ] [Language Models are Unsupervised Multitask Learners - a.k.a GPT-2](https://d4mucfpksywv.cloudfront.net/better-language-models/language_models_are_unsupervised_multitask_learners.pdf)
- [ ] [Advances and Open Problems in Federated Learning](https://arxiv.org/pdf/1912.04977.pdf)
- [ ] [On the Measure of Intelligence](https://arxiv.org/abs/1911.01547)
- [ ] [Single Headed Attention RNN: Stop Thinking With Your Head](https://arxiv.org/abs/1911.11423)
- [ ] [Towards Empathetic Open-domain Conversation Models: a New Benchmark and Dataset](https://arxiv.org/abs/1811.00207)
- [ ] [The Next Decade in AI: Four Steps Towards Robust Artificial Intelligence
](https://arxiv.org/abs/2002.06177)
- [ ] [Deep Learning Based Text Classification: A Comprehensive Review](https://deepai.org/publication/deep-learning-based-text-classification-a-comprehensive-review)
- [ ] [The Problem with Metrics is a Fundamental Problem for AI](https://arxiv.org/abs/2002.08512)
- [ ] [A Simple Framework for Contrastive Learning of Visual Representations](https://arxiv.org/abs/2002.05709)
- [ ] [Growing Neural Cellular Automata](https://distill.pub/2020/growing-ca/)
- [ ] [Attention is not Explanation](https://arxiv.org/abs/1902.10186)
- [ ] [Deep Learning for Symbolic Mathematics](https://arxiv.org/abs/1912.01412)
- [ ] [Self-Distillation Amplifies Regularization in Hilbert Space](https://arxiv.org/abs/2002.05715)
- [ ] [Distilling the Knowledge in a Neural Network](https://arxiv.org/pdf/1503.02531.pdf)

**Comment by manisnesan** [comment]
@omarsar I started reading this paper[1] & summarized it here https://forums.fast.ai/t/question-answering-system-for-covid-19/68374 . Would appreciate review and feedback.

[1] [Rapidly Deploying a Neural Search Engine for the COVID-19 Open Research Dataset: Preliminary Thoughts and Lessons Learned](https://openreview.net/forum?id=PlUA_mgGaPq)

**Comment by manisnesan** [comment]
@omarsar  Will convert the above summary into google doc for review & feedback

**Comment by omarsar** [comment]
@manisnesan looking forward to it!

**Comment by omarsar** [comment]
Group paper presentation task for the EXTREME paper #72

**Comment by constanzafierro** [comment]
Hey @omarsar I’d be interested in doing the summary for “Attention is all you need”

**Comment by omarsar** [comment]
@cfierro94 This will be great! Let me know if you have any questions or need feedback/help with the process.

**Comment by AntonioLopardo** [comment]
I would like to work on [BART](https://arxiv.org/abs/1910.13461)

**Comment by ngc436** [comment]
I would like to take ELECTRA paper

**Comment by omarsar** [comment]
@JessikaSmith that would be great! Are you on our slack channel group? If not, I can send you an invite.

**Comment by ngc436** [comment]
@omarsar Thanks, I am already on the slack channel

**Comment by Viktor2k** [comment]
Started to summarize Longformer!

**Comment by omarsar** [comment]
I am working on the "Experience Grounds Knowledge" paper.

**Comment by laibamehnaz** [comment]
Hi @omarsar, 
I will be working on ERNIE 2.0 :)

**Comment by abhirup-dev** [comment]
@omarsar I would like to write about Knowledge Distillation

**Comment by omarsar** [comment]
@maverickdas thanks for your interest to contribute here. Are you thinking of a paper summary or just a survey of the works?

**Comment by skeshaw** [comment]
Hi @omarsar,
I would like to take up the paper "Byte Pair Encoding is Suboptimal for Language Model Pretraining."

**Comment by omarsar** [comment]
@skeshaw Absolutely! That would be a nice paper summary. Let me know if you need any help getting started. :)

**Comment by abhirup-dev** [comment]
> @maverickdas thanks for your interest to contribute here. Are you thinking of a paper summary or just a survey of the works?

Sorry for the late reply @omarsar. I was thinking of a survey of the works.

**Comment by constanzafierro** [comment]
Hey there, I'm going to start working on the " BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding" summary!

**Comment by Viktor2k** [comment]
@omarsar  Done with Longformer, please sign me up on _What Does BERT Look At?_

**Comment by Viktor2k** [comment]
@omarsar Done with that too :)

**Comment by omarsar** [comment]
@Viktor2k great work! I fixed a few typos and published it. Thanks!

**Comment by constanzafierro** [comment]
I’m currently working on “recipes for building an open-domain chatbot”

**Comment by reemalyami** [comment]
Hi Omar 

I would like to write about "Ethical considerations in NLP"

**Comment by omarsar** [comment]
@reemalyami  Thank you! Let me know if you have any ideas in mind.

**Comment by srichakradhar** [comment]
Hi @omarsar I found [this](https://www.aclweb.org/anthology/P19-1487.pdf) ACL paper interesting. I also have read the paper and made a presentation summary: https://drive.google.com/file/d/15QACtsjCiBik6uyuHFXroVcTWL0EiUue/view?usp=sharing Any review and feedback is appreciated.

**Comment by omarsar** [comment]
@srichakradhar would you like to work on a paper presentation or paper summary? I will provide you some feedback as soon as I get a chance. Thanks.

**Comment by srichakradhar** [comment]
Sure @omarsar That'd be awesome! Although I have not presented a paper in a meetup format before, I'd love to do it, with your inputs. :)

**Comment by tshrjn** [comment]
I'd like to work on REALM.

**Comment by omarsar** [comment]
@tshrjn That's great. Let me know if you need any help.

**Comment by AntonioLopardo** [comment]
I would enjoy working on the Reformer Summary

**Comment by vsistla** [comment]
@omarsar  - would like to work on "A Primer in BERTology: What we know about how BERT works" - https://arxiv.org/abs/2002.12327

Let me know if someone else is already working on it. I can partner with them if that is the case.

**Comment by omarsar** [comment]
@AntonioLopardo , @vsistla awesome! Those are both great papers worth summarizing. Let us know if you need any help. :)

**Comment by omarsar** [comment]
> I would enjoy working on the Reformer Summary

@AntonioLopardo  please open a separate issue for this and link it back here. Thanks

**Comment by omarsar** [comment]
> @omarsar - would like to work on "A Primer in BERTology: What we know about how BERT works" - https://arxiv.org/abs/2002.12327
> 
> Let me know if someone else is already working on it. I can partner with them if that is the case.

@vsistla please open a separate issue for this and link it back here. Thanks

**Comment by abhinavkashyap** [comment]
@omarsar If no one is summarising  `Climbing towards NLU: On Meaning, Form, and Understanding in the Age of Data`. I would like to summarise this paper.

**Comment by omarsar** [comment]
> @omarsar If no one is summarising `Climbing towards NLU: On Meaning, Form, and Understanding in the Age of Data`. I would like to summarise this paper

@abhinavkashyap please open an issue in this repository and link back to this issue using #27. Here is an [example](https://github.com/dair-ai/dair-ai.github.io/issues/120) of how you would do this. We will assign you an editor as well to help you in the process (nothing too formal but it helps to have someone that can guide you in the process). You can also join our Slack channel for any questions you may have. Thanks.

**Comment by mmiakashs** [comment]
Thanks for this initiative, I would love to write summaries for the following three papers (incrementally). If anyone is working on these papers I would love to collaborate. Let me know 

- Distilling the Knowledge in a Neural Network
- A Simple Framework for Contrastive Learning of Visual Representations
- Attention is not Explanation

**Comment by skeshaw** [comment]
@mmiakashs Hi! You can open a separate issue for each paper summary that you are working on and link it to this repo. The process is outlined in the comment just above yours by Elvis. Let us know if you need any help.

**Comment by omarsar** [comment]
> Thanks for this initiative, I would love to write summaries for the following three papers (incrementally). If anyone is working on these papers I would love to collaborate. Let me know
> 
> * Distilling the Knowledge in a Neural Network
> * A Simple Framework for Contrastive Learning of Visual Representations
> * Attention is not Explanation

@mmiakashs They are all great choices. If I can suggest, maybe start with the earliest paper which is "Distilling the Knowledge in a Neural Network". Then the other two can be done in whatever order you like -- they are relatively recent papers.

Please also note that when you are working on a paper, it would be nice to open an issue and link it back here. There are some examples in this thread. Let us know if you have any further questions.

**Comment by omarsar** [comment]
Hi folks, going forward I will be suggesting papers worth summarizing directly in this repository: https://github.com/dair-ai/nlp_paper_summaries/issues

Also, there were a lot of you working on paper summaries. Any updates on these? We will be happy to help if you need it. Thanks.
